# -*- coding: utf-8 -*-
"""真值表

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pQxoOwB0Zh13fCphI9ySSVu-jr8_ESiu
"""

row ="{:^10}{:^10}{:^10}{:^10}{:^10}{:^10}{:^10}"
print(row.format("P","Q","P∧Q","P∨Q","P→Q","P←Q","P↔Q"))
print(row.format("F","F","F","F","T","T","T"))
print(row.format("F","T","F","T","T","F","F"))
print(row.format("T","F","F","T","F","T","F"))
print(row.format("T","T","T","T","T","T","T"))